src/App.tsx
src/AppFederated.tsx
src/app/OBInstance/OBInstancePage/OBInstancePage.tsx
src/app/OBInstance/OBInstancesListPage/OBInstancesListPage.tsx
src/app/OBRoutes/OBRoutes.tsx

[MGDOBR-375] Setup internal routing

---

jest.config.ts
package-lock.json
package.json
src/app/components/AppLayout/AppLayout.test.tsx

https://issues.redhat.com/browse/MGDOBR-459

[MGDOBR-459]: Configure a test runner for the React application

---

openapi/generated/api.ts
openapi/generated/api/bridges-api.ts
openapi/generated/api/error-catalog-api.ts
openapi/generated/api/processors-api.ts
openapi/generated/api/shard-api.ts
openapi/smart-events.yaml
scripts/generate_openapi_client.sh

This is a follow-up task due to:
https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/504

MGDOBR-420: Simplify SDK api suffix

---

package-lock.json
package.json
src/App.tsx
src/Keycloak.tsx
src/app/components/AppLayout/AppLayout.tsx

https://issues.redhat.com/browse/MGDOBR-413
This PR adds keycloak authentication to the standalone UI app to allow local API integration.
The keyclock config will change after sso will be added ([see 466](https://issues.redhat.com/browse/MGDOBR-466)). 
After that it will be possible to test the authentication with the SE as federated module.
- `npm install`
- `npm run start`

[MGDOBR-413] Configure keycloak authentication

---

locales/en/openbridge.json
src/App.tsx
src/app/Instance/CreateInstance/CreateInstance.test.tsx
src/app/Instance/CreateInstance/CreateInstance.tsx
src/app/Instance/InstancesListPage/InstancesListPage.tsx

https://issues.redhat.com/browse/MGDOBR-418
It follows https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/13 to use the test setup available there.
If you are reviewing this PR before #13 is merged, please filter only the last commit (_"MGDOBR-418: add CreateInstance component"_)
Steps to open it:
- `npm run start`
- login
- click on "Create Smart Events instance"

MGDOBR-418: "Create Smart Events instance" template 

---

.eslintrc.js
src/App.tsx
src/AppFederated.tsx
src/Keycloak.tsx
src/app/Instance/CreateInstance/CreateInstance.test.tsx
src/app/Instance/CreateInstance/CreateInstance.tsx
src/app/Instance/InstancePage/InstancePage.tsx
src/app/Instance/InstancesListPage/InstancesListPage.tsx
src/app/Processor/CreateProcessorPage/CreateProcessorPage.tsx
src/app/Processor/ProcessorDetail/ProcessorDetail.tsx
src/app/Processor/ProcessorDetailPage/ProcessorDetailPage.tsx
src/app/Processor/ProcessorEdit/ActionEdit/ActionEdit.tsx
src/app/Processor/ProcessorEdit/FiltersEdit/FiltersEdit.tsx
src/app/Processor/ProcessorEdit/ProcessorEdit.test.tsx
src/app/Processor/ProcessorEdit/ProcessorEdit.tsx
src/app/Processor/ProcessorEdit/SourceEdit/SourceEdit.tsx
src/app/Routes/Routes.tsx
src/app/components/AppLayout/AppLayout.tsx
src/app/components/Breadcrumb/Breadcrumb.tsx
src/app/components/Pagination/Pagination.tsx
src/app/components/Table/Table.test.tsx
src/app/components/Table/Table.tsx
src/app/components/TableWithPagination/TableWithPagination.tsx
src/utils/testUtils.tsx

For more details, see the jira:
- https://issues.redhat.com/browse/MGDOBR-530

MGDOBR-530: Fix missing explicit function types

---

locales/en/openbridge.json
src/app/Instance/InstancePage/InstancePage.tsx
src/app/Instance/InstancesListPage/InstancesListPage.tsx
src/app/Processor/CreateProcessorPage/CreateProcessorPage.tsx
src/app/Processor/ProcessorDetailPage/ProcessorDetailPage.tsx
src/app/components/StatusLabel/StatusLabel.tsx

https://issues.redhat.com/browse/MGDOBR-544
With this PR I'm addressing minor changes to improve the overall demo of the static UI.
It's mostly about improving consistency of names, statuses and spacing across different pages. See jira link for more info.

MGDOBR-544: Various refinements

---

.github/workflows/build.yml

For more details see:
- https://issues.redhat.com/browse/MGDOBR-611

MGDOBR-611: Build project with every PR

---

README.md
package.json
webpack.common.js

Changing exposed component name to something more descriptive. Also making federate module name more readable.

NO-JIRA: Renaming federated module and exposed component

---

cypress/integration/smoke/BasicTest.ts
openapi/generated/model/managed-resource-status.ts
openapi/generated/model/processor-type.ts
openapi/smart-events.yaml
scripts/openapitools.json
src/app/components/AppLayout/AppLayout.tsx

See: https://issues.redhat.com/browse/MGDOBR-601

MGDOBR-601: [UI] OUIA in navigation items

---

cypress/integration/InstancesTest.ts
cypress/integration/smoke/BasicTest.ts
src/app/Instance/CreateInstance/CreateInstance.tsx
src/app/Instance/InstanceDetails/InstanceDetails.tsx
src/app/Instance/InstancePage/InstancePage.tsx
src/app/Instance/InstancesListPage/InstancesListPage.tsx
src/app/components/Table/Table.tsx
src/app/components/TableWithPagination/TableWithPagination.tsx
src/app/components/TableWithPaginationSkeleton/TableWithPaginationSkeleton.tsx

See: https://issues.redhat.com/browse/MGDOBR-654

MGDOBR-654: [UI] OUIA in the 'Instance' component

---

cypress/integration/smoke/BasicTest.ts

Jira:[https://issues.redhat.com/browse/MGDOBR-699](https://issues.redhat.com/browse/MGDOBR-699)

MGDOBR-699:[UI] add test for checking instance header details

---

locales/en/openbridge.json
src/app/Processor/CreateProcessorPage/CreateProcessorPage.tsx
src/app/Processor/ProcessorEdit/ActionEdit/ActionEdit.tsx
src/app/Processor/ProcessorEdit/ProcessorEdit.css
src/app/Processor/ProcessorEdit/ProcessorEdit.test.tsx
src/app/Processor/ProcessorEdit/ProcessorEdit.tsx
src/app/Processor/ProcessorEdit/ProcessorEditSkeleton.tsx
src/app/Processor/ProcessorEdit/SourceEdit/SourceEdit.tsx
src/app/Processor/ProcessorEdit/useValidateConfigParams.ts
src/app/Processor/ProcessorEdit/useValidateProcessor.ts
src/app/Processor/ProcessorEdit/useValidationBase.ts
src/hooks/useProcessorsApi/useAddProcessorToBridgeApi.ts
src/types/Error.ts
src/types/Processor.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-675
This PR is dependent on #40
- `npm run start:mocked`
- open the create processor page: `http://localhost:8080/instance/3543edaa-1851-4ad7-96be-ebde7d20d717/create-processor`
While reviewing, you can filter only the last commit (60246e4) until #40 is merged.

MGDOBR-675: Plug processors creation to APIs

---

locales/en/openbridge.json
src/app/Instance/CreateInstance/CreateInstance.tsx
src/app/Instance/InstancesListPage/InstancesListPage.tsx
src/hooks/useBridgesApi/useCreateBridgeApi.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-671

MGDOBR-671: Plug SE instance creation to APIs

---

package.json

https://issues.redhat.com/browse/MGDOBR-760
Tests with electron
Tests with chrome

MGDOBR-760: Run cypress tests on chrome

---

locales/en/openbridge.json
src/app/Instance/InstancePage/InstancePage.tsx
src/app/Processor/DeleteProcessor/DeleteProcessor.tsx
src/app/Processor/ProcessorDetailPage/ProcessorDetailPage.tsx
src/hooks/useProcessorsApi/useDeleteProcessorApi.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-676
This PR depends on #52.
~Also I'm keeping it as draft for now because it will need some refactoring after #54.~
To test this PR, you can delete a processor from the processor detail page (through the `Actions` dropdown) or from the processors table inside a SE Instance page.
Keep in mind that only processors in final states (`ready`, `failed`) can be deleted.
>**Note**
>If you are reviewing this before #52 is merged, only filter the last two commits (the ones starting with `MGDOBR-676`)

MGDOBR-676: Plug processors deletion to APIs

---

cypress/integration/smoke/BasicTest.ts
src/app/Processor/CreateProcessorPage/CreateProcessorPage.tsx
src/app/Processor/ProcessorDetail/ProcessorDetail.tsx
src/app/Processor/ProcessorDetailPage/ProcessorDetailPage.tsx
src/app/Processor/ProcessorEdit/ActionEdit/ActionEdit.tsx
src/app/Processor/ProcessorEdit/FiltersEdit/FiltersEdit.tsx
src/app/Processor/ProcessorEdit/ProcessorEdit.tsx
src/app/Processor/ProcessorEdit/SourceEdit/SourceEdit.tsx

https://issues.redhat.com/browse/MGDOBR-723

MGDOBR-723: OUIA in the  component

---

config/config.ts
src/App.tsx
src/AppMocked.tsx
src/Keycloak.tsx
src/hooks/useBridgesApi/useCreateBridgeApi.ts
src/hooks/useBridgesApi/useDeleteBridgeApi.ts
src/hooks/useBridgesApi/useGetBridgeApi.ts
src/hooks/useBridgesApi/useGetBridgesApi.ts
src/hooks/useProcessorsApi/useAddProcessorToBridgeApi.ts
src/hooks/useProcessorsApi/useDeleteProcessorApi.ts
src/hooks/useProcessorsApi/useGetProcessorApi.ts
src/hooks/useProcessorsApi/useGetProcessorsApi.ts
src/hooks/useProcessorsApi/useUpdateProcessorApi.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-742

MGDOBR-742: Set up config context and update auth context

---

.github/workflows/openapi-sdk-compatibility-check.yml
scripts/fetch_openapi.sh

Hi,
updates to reflect changes made in pr#793 in ```sandbox``` to avoid errors. 
Thanks

chore: follow up update to pr#793 in sandbox

---

cypress/integration/DeleteTest.ts
src/app/Instance/DeleteInstance/DeleteInstance.tsx
src/app/Processor/DeleteProcessor/DeleteProcessor.tsx
src/app/components/DeleteModal/DeleteModal.test.tsx
src/app/components/DeleteModal/DeleteModal.tsx

For more details see:
- https://issues.redhat.com/browse/MGDOBR-676
- https://issues.redhat.com/browse/MGDOBR-677

MGDOBR-676,677: Cover delete Processor and Instance

---

src/app/components/DeleteModal/DeleteModal.test.tsx

This PR is a follow up task after discussion on other PR:
https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/63#issuecomment-1141802492

MGDOBR-6767,677: Check delete button is disabled for wrong confirmation

---

cypress/integration/InstancesTest.ts

https://issues.redhat.com/browse/MGDOBR-712

MGDOBR-712 - [UI] added test for verifying processor header details

---

mocked-api/schemasData.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-873
Checking the new kafka topic sink. No issues found. Just updating the corresponding mock.

MGDOBR-873: Verify the new kafka topic action is properly supported by the UI

---

.github/workflows/openapi-sdk-compatibility-check.yml
scripts/openapi-sdk/fetch_openapi.sh

To be merged together with 
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/925

Align scripts to new rhose-api name (smartevents_mgmt)

---

.husky/pre-commit

For more details see:
- https://prettier.io/docs/en/precommit.html#option-6-shell-script

[NO-JIRA] Format just staged files

---

cypress/README.md
cypress/cypress.e2e.json
cypress/e2e/BasicTest.ts
cypress/tsconfig.json
package.json

https://issues.redhat.com/browse/MGDOBR-790
I have created a simple test which send data via REST API and then check if they are present in UI.
All neccessary steps should be mentioned in README.
This test is not a part of GHA (right now) but it is possible to run it locally.

MGDOBR-790: [UI] E2E tests - Create PoC

---

mocked-api/schemasData.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-937
Hopefully this is the last one!
Form generated from schema works fine. Needed changes are logged inside [MGDOBR-901](https://issues.redhat.com/browse/MGDOBR-901). For now it's just the Service Account Key missing the proper password definition.

MGDOBR-937: Verify new Google PubSub source processor

---

cypress/integration/InstancesTest.ts
locales/en/openbridge.json
src/app/Instance/InstanceDetails/InstanceDetails.tsx

**Task**: https://issues.redhat.com/browse/MGDOBR-944

MGDOBR-944: Ingress endpoint copy update + use compact version of PF copy component

---

mocked-api/handlers.ts
openapi/generated/model/bridge-list-response.ts
openapi/generated/model/bridge-response.ts
openapi/generated/model/cloud-provider-list-response.ts
openapi/generated/model/cloud-provider-response.ts
openapi/generated/model/cloud-region-list-response.ts
openapi/generated/model/cloud-region-response.ts
openapi/generated/model/error-list-response.ts
openapi/generated/model/error-response.ts
openapi/generated/model/errors-response.ts
openapi/generated/model/processor-catalog-response.ts
openapi/generated/model/processor-list-response.ts
openapi/generated/model/processor-response.ts
openapi/generated/model/processor-schema-entry-response.ts
openapi/smart-events.yaml
src/app/Instance/InstancePage/InstancePage.tsx
src/app/Instance/InstancesListPage/InstancesListPage.tsx
src/app/Processor/ProcessorDetailPage/ProcessorDetailPage.tsx
src/app/Processor/ProcessorEdit/ProcessorEdit.test.tsx

Related to PR https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/957
Building `sandbox-ui` with latest backend openapi spec throws:
```
ERROR in /home/jomarko/redhat/smart-events/sandbox-ui/mocked-api/handlers.ts
./mocked-api/handlers.ts 975:2-41
[tsl] ERROR in /home/jomarko/redhat/smart-events/sandbox-ui/mocked-api/handlers.ts(975,3)
TS2740: Type 'Omit<Record<string, unknown>, string>' is missing the following properties from type 'ProcessorResponse': 'kind', 'id', 'href', 'submitted_at', and 3 more.
@ ./mocked-api/browser.ts 2:0-38 4:37-45
@ ./src/AppMocked.tsx
@ ./src/bootstrap.tsx 4:0-36 7:40-49
@ ./src/index.tsx
```

MGDOBR-683:  Update sandbox-ui openapi-sdk

---

cypress/integration/ActionTest.ts
src/app/Processor/ProcessorEdit/ConfigurationForm/ConfigurationForm.tsx
src/app/Processor/ProcessorEdit/ProcessorEdit.tsx

https://issues.redhat.com/browse/MGDOBR-967
Create new test suite for the configuration of Processor's actions.

MGDOBR-967: Add action definition test

---

cypress/e2e/BasicTest.ts
cypress/integration/DeleteTest.ts
cypress/integration/InstancesTest.ts
cypress/integration/smoke/BasicTest.ts
src/app/Instance/InstancePage/InstancePage.tsx
src/app/Instance/InstancesListPage/InstancesListPage.tsx

**Task**: https://issues.redhat.com/browse/MGDOBR-945

MGDOBR-945: Changes to overview table columns

---

mocked-api/schemasData.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-971

MGDOBR-971: Verify new Azure Event Hubs source schema

---

mocked-api/schemasData.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-996
Updating mocked schemas following [#998](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/998) and [#962](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/966)

MGDOBR-996: Update mocked schemas following update from connectors

---

cypress/integration/DeleteTest.ts
cypress/integration/InstancesTest.ts
cypress/integration/Util.ts

https://issues.redhat.com/browse/MGDOBR-717

MGDOBR-717 - [UI] added test for Instance List pagination

---

locales/en/openbridge.json
src/app/Processor/ProcessorEdit/ProcessorEdit.tsx

**Task**: https://issues.redhat.com/browse/MGDOBR-948

MGDOBR-948: Add information about the transformation template language

---

renovate.json

- Ui modules of managed services https://github.com/bf2fc6cc711aee1a0c2a usess slightly different renovate configuration as sandbox-ui is using currently.
- Renovate community advice to use property for approving upgrades in dashboard https://github.com/renovatebot/renovate/discussions/17426#discussioncomment-3482988

Update Renovate according to kas-ui, srs-ui and kafka-ui

---

.github/workflows/quality-checks-e2e.yml

https://issues.redhat.com/browse/MGDOBR-970
This code has to be merge in the main branch to perform correctly the `workflow_dispatch` event.
The previous change does not help: https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/160
Additonal info: https://issues.redhat.com/browse/MGDOBR-300

MGDOBR-970: E2E - manual execution of GHA is failing in the checkout

---

mocked-api/schemasData.ts

This PR aligns mocked data with changes on backend, especially with changes https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/1116

MGDOBR-1066: Align mocked data with backend

---

.github/workflows/update-pr-title-and-label.yml
renovate.json

for more details: https://issues.redhat.com/browse/MGDOBR-1047

MGDOBR-1047: Add [Renovate] prefix for PR created by Renovate bot

---

cypress/integration/ActionTest.ts
mocked-api/schemasData.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-972
Adding new action mock following [#184](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/824).
Looks O.K.
Logged new action inside [MGDOBR-901](https://issues.redhat.com/browse/MGDOBR-901)

MGDOBR-972: Verify new Azure Event Hubs action schema

---

cypress/integration/InstancesTest.ts
src/app/Instance/InstancePage/ErrorHandlingTabContent.tsx
src/app/Processor/ProcessorConfigParameters/ProcessorConfigParameters.tsx

MGDOBR-985: add error handling cypress tests

---

.github/workflows/update-pr-title-and-label.yml

For more details see: https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/205#issuecomment-1263181436

[No-jira] Fix update-pr-title-and-label action

---

locales/en/openbridge.json
src/app/Instance/InstanceDetails/InstanceDetails.tsx
src/types/CloudProviders.ts

JIRA:  https://issues.redhat.com/browse/MGDOBR-928
Steps to test it (on chrome):
- Open the drawer of smart event instance details. 
- It will display the Cloud Provider and Cloud Region information of the instance.
- Also try to create a new Instance and check the drawer for the same.
- If the providers are not available then it will display Cloud Provider and Cloud Region  as "Not available".

MGDOBR-928: Display cloud provider/region information of a Bridge

---

mocked-api/handlers.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-1118
Now when creating a bridge/processor with mocked APIs, it will go through the proper status flow (`accepted` :arrow_right: `preparing` :arrow_right: `provisioning` :arrow_right: `ready`)

MGDOBR-1118: Create bridge: the mocked version should go througt all states

---

cypress/support/commands.ts

https://issues.redhat.com/browse/MGDOBR-1133
This PR presents the hot fix: check if the popover is presented and if yes than click at the 'Accept default' button.

MGDOBR-1133: [UI] SSO shows a cookie's popover

---

src/app/Instance/CreateInstance/CreateInstance.test.tsx
src/app/Instance/CreateInstance/CreateInstance.tsx
src/app/Instance/CreateInstance/components/InstanceNameField.tsx
src/app/Instance/CreateInstance/machines/cloudProvidersMachine.ts
src/app/Instance/CreateInstance/machines/createInstanceMachine.ts
src/app/Instance/CreateInstance/machines/createInstanceMachine.typegen.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-1125
The issue was only present when creating a bridge with an EH configuration without encountering validation errors.

MGDOBR-1125: New Instance creation ignores Error Handler definition

---

locales/en/openbridge.json
mocked-api/data.ts
mocked-api/handlers.ts
src/app/Instance/ErrorHandling/ErrorHandlingCreate.tsx
src/app/Instance/ErrorHandling/ErrorHandlingDetail.test.tsx
src/app/Instance/ErrorHandling/ErrorHandlingDetail.tsx
src/app/Instance/InstancePage/ErrorHandlingTabContent.tsx
src/types/ErrorHandlingMethods.ts

**Task**: https://issues.redhat.com/browse/MGDOBR-1056
**Note**: There was no mockup or specific directive on displaying the Error endpoint URL. So, please consider the proposed layout and the description text.
**Screenshots**:

MGDOBR-1056: Support the "endpoint" error handling strategy

---

src/app/Processor/ProcessorDetail/ProcessorDetail.tsx
src/app/Processor/ProcessorDetailPage/ProcessorDetailPage.tsx
src/app/components/SEStatusLabel/SEStatusLabel.tsx
src/app/components/SEStatusLabel/useResourceDelayedStatus.test.ts
src/app/components/SEStatusLabel/useResourceDelayedStatus.ts
src/hooks/usePolling/usePolling.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-1148

MGDOBR-1148: Refresh processor detail information during creation/update process

---

src/app/Processor/ProcessorEdit/useValidateProcessor.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-757

MGDOBR-757: Fix lodash usage as transitive dependency

---

src/app/Instance/InstancePage/ProcessorsTabContent.tsx
src/app/Instance/InstancesListPage/InstancesListPage.tsx
src/app/components/PageNotFound/PageNotFound.tsx

JIRA: https://issues.redhat.com/browse/MGDOBR-1165

MGDOBR-1165: Fix heading levels within empty and error UI states

---

package-lock.json

npm install was returning:
```
jomarko@localhost sandbox-ui (main)$ npm install
> smartevents-ui@0.0.1 prepare
> husky install
husky - Git hooks installed
added 13 packages, removed 61 packages, changed 5 packages, and audited 1468 packages in 8s
184 packages are looking for funding
run `npm fund` for details
3 vulnerabilities (2 high, 1 critical)
To address all issues, run:
npm audit fix
Run `npm audit` for details.
```
This PR contains changes done by `npm audit fix`

[no-jira] Fix npm vulnerabilities

---

cypress/integration/instance/InstanceEdit.ts
src/app/Instance/ErrorHandling/ErrorHandlingSelection.tsx

For more details see: https://issues.redhat.com/browse/MGDOBR-1095
This PR is in a 'draft' due to some internal refactoring done in #193 and fix in #207

MGDOBR-1095: Add error handling strategy switch tests

---

src/app/Instance/InstancePage/InstancePage.tsx
src/app/Instance/InstancesListPage/InstancesListPage.tsx

JIRA: https://issues.redhat.com/browse/MGDOBR-1119
Steps to test it (on chrome):
- Create a bridge instance with Incorrect parameters to enter into Failed state.
- Then it will allow to edit the bridge instance.
- Also, the status label of the bridge is visible on the Instance Page.

MGDOBR-1119:Allow the bridge instance to edit in case of instance is in FAILED status

---

cypress/integration/ProcessorTest.ts
cypress/integration/instance/InstanceCreation.ts
locales/en/smart-events.json
mocked-api/handlers.ts
openapi/generated/errors.ts
src/app/Instance/CreateInstance/components/InstanceAlert.tsx
src/app/Instance/CreateInstance/types.ts
src/app/Processor/CreateProcessorPage/CreateProcessorPage.tsx
src/hooks/useBridgesApi/useCreateBridgeApi.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-1181
Steps to test it (on chrome):
- Try to create a new bridge instance with name containing "quota-error".
- Submit the form by clicking on Create Smart Events Instance.
- alert will appear on the top of the form.
- Also try to create a new processor with name containing "quota-error".
- It will display a modal with error message.

MGDOBR-1181: Add service limits errors management when creating bridges and processors.

---

cypress/integration/ActionTest.ts
cypress/integration/DeleteTest.ts
cypress/integration/ProcessorTest.ts
cypress/integration/SourceTest.ts
cypress/integration/instance/InstanceCreation.ts
cypress/integration/instance/InstanceEdit.ts
cypress/integration/instance/InstancePage.ts
cypress/integration/instance/InstanceStatuses.ts
cypress/integration/instance/Pagination.ts
cypress/integration/smoke/BasicTest.ts
cypress/integration/smoke/RESTInteractionTest.ts
cypress/support/commands.ts
cypress/utils/Util.ts

https://issues.redhat.com/browse/MGDOBR-1133
I will run GHA 15 times to be sure that the popover form is not occured.
Results:
**Smart Events UI :: Dev :: Quality Checks -> 12/15 runs passed**
A. first failure should be corrected by using "Domain: .redhat.com" - related with this issue
B. not sure why the visit command does not redirect page to SSO - not sure if it is related
C. Unexpected failure -> UI is not expected ... need investigation - this shouldnt be related with this issue
**Smart Events UI :: Mocked :: Quality Checks -> 14/15 runs passed**
A. Error during loading the page - not related with code
**Smart Events UI :: Build -> 15/15 runs passed**

MGDOBR-1133: Insert cookies to avoid the cookies popover form

---

cypress/integration/smoke/RESTInteractionTest.ts

The problem occurs in 
https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/262
https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/261
The problem is that the timeout is probably too small.

no-jira: fix timeout in RESTInteractionTest

---

cypress/README.md
cypress/integration/instance/InstanceCreation.ts
cypress/integration/instance/InstancePage.ts
cypress/integration/instance/InstanceStatuses.ts
cypress/integration/instance/Pagination.ts
cypress/integration/smoke/BasicTest.ts
cypress/integration/smoke/RESTInteractionTest.ts
cypress/support/commands.d.ts
cypress/support/commands.ts
cypress/utils/Config.ts
cypress/utils/Util.ts

https://issues.redhat.com/browse/MGDOBR-1041

MGDOBR-1041: Check Environment Configuration in Test Suite

---

cypress/integration/instance/InstanceStatuses.ts
cypress/support/commands.d.ts
cypress/support/commands.ts
cypress/utils/Util.ts

PR #262 contains several errors in Typescript build. It seems that is not possible to import trivialy objects into command files.

MGDOBR-1041: fix errors in Typescript build

---

.storybook/main.js
package-lock.json
package.json
src/app/Processor/ProcessorEdit/ProcessorEdit.tsx
src/app/components/POCs/CamelDSLCodeEditor/CamelDSLCodeEditor.css
src/app/components/POCs/CamelDSLCodeEditor/CamelDSLCodeEditor.stories.tsx
src/app/components/POCs/CamelDSLCodeEditor/CamelDSLCodeEditor.tsx
src/app/components/POCs/CamelDSLCodeEditor/camelDSLSchema.json
src/app/components/POCs/CamelDSLCodeEditor/camelDSLutils.ts
webpack.common.js

JIRA: https://issues.redhat.com/browse/MGDOBR-1317
You can try the editor by running storybook locally with `npm run storybook` or by clicking on the `Storybook Publish` link within this PR checks list.

MGDOBR-1317: Add CamelDSL code editor PoC to storybook

---

locales/en/smart-events.json
src/app/components/POCs/CamelDSLCodeEditor/CamelDSLCodeEditor.css
src/app/components/POCs/CamelDSLCodeEditor/CamelDSLCodeEditor.stories.tsx
src/app/components/POCs/CamelDSLCodeEditor/CamelDSLCodeEditor.tsx
src/app/components/POCs/CamelDSLCodeEditor/camelDSLSchema.json
src/app/components/POCs/ProcessorCodeEditor/ProcessorCodeEditor.css
src/app/components/POCs/ProcessorCodeEditor/ProcessorCodeEditor.stories.tsx
src/app/components/POCs/ProcessorCodeEditor/ProcessorCodeEditor.tsx

JIRA: https://issues.redhat.com/browse/MGDOBR-1338
I've wrapped the code editor in a flex layout to make it fill all the vertical space available. I've also added validation listeners to be able to detect if there are errors in the code. It's likely we are going to disable saving invalid processors.

MGDOBR-1338: "Create processor" step 2 poc component

---

mocked-api/handlers.ts
openapi/generated/errors.ts
src/app/Instance/DeleteInstance/DeleteInstance.tsx
src/app/Instance/InstancePage/InstancePage.tsx
src/app/Processor/CreateProcessorPage/CreateProcessorPage.tsx
src/app/Processor/DeleteProcessor/DeleteProcessor.tsx
src/app/Processor/ProcessorDetailPage/ProcessorDetailPage.tsx
src/hooks/useBridgesApi/useCreateBridgeApi.ts

JIRA: https://issues.redhat.com/browse/MGDOBR-1405

MGDOBR-1405: Update TS errors catalog and server side errors management

---

src/app/Instance/BridgeOverview/BridgeOverview.stories.tsx
src/app/Instance/BridgeOverview/BridgeOverview.test.tsx
src/app/Instance/BridgeOverview/BridgeOverview.tsx
src/app/Instance/BridgeOverview/Components/BODashboardTableView.tsx
src/app/Instance/BridgeOverview/Components/BOProcessorList.tsx
src/app/Instance/BridgeOverview/Components/BOSinkList.tsx
src/app/Instance/BridgeOverview/Components/BOSourceList.tsx
src/app/Instance/InstancePage/BridgeOverviewTabContent.tsx

JIRA: https://issues.redhat.com/browse/MGDOBR-1426

MGDOBR-1426: Handle processor edit/delete features inside bridge overview
