5733d9e2be6485d52ffa08870cabdee0/sandbox-ui

- locales/en/openbridge.json
- package-lock.json
- package.json
- src/App.tsx
- src/AppFederated.tsx
- src/app/OBInstance/OBInstancesListPage/OBInstancesListPage.tsx
- src/types/global.d.ts
- webpack.common.js
https://issues.redhat.com/browse/MGDOBR-393
I've added a translation to display the "Demo Overview" title in the main page as a way to test the i18n setup.
You can run the OB application in standalone mode following the instructions in the [README](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui#readme).
To run the OB federated module while we still don't have proper `app-services-ui` integration, you can follow this steps:
- first run `sandbox-ui` in federated mode using `npm run start:federate`
- clone the `OB-route` branch of [my fork of app-services-ui](https://github.com/kelvah/app-services-ui/tree/OB-route)
- run `npm install` and then `npm start:dev` in the `app-services-ui` app
- open the following url in the browser: …
> [MGDOBR-393]: Configure i18n and setup default EN locale dictionary

- README.md
- package-lock.json
- package.json
- src/App.tsx
- src/AppFederated.tsx
- src/app/Instance/InstancePage/InstancePage.tsx
- src/app/Instance/InstancesListPage/InstancesListPage.tsx
- src/app/Routes/Routes.tsx
- src/app/components/AppLayout/AppLayout.tsx
- webpack.common.js
https://issues.redhat.com/browse/MGDOBR-432
For running it, you can follow the same instructions of https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/4 except that (for the federated scenario) you should refer to [my fork of app-services-ui](https://github.com/vpellegrino/app-services-ui/tree/SE-route) and you should open the URL https://prod.foo.redhat.com:1337/beta/application-services/smartevents
> [MGDOBR-432]: Rename codebase references from "open-bridge" to "smart-events"

- .prettierrc
https://issues.redhat.com/browse/MGDOBR-600
I'm removing two invalid properties from `.prettierrc`. They are causing dozens of warnings while running `npm run format:check`, something like: 
```
[warn] Ignored unknown option { importOrder: ["^@?xstate/?(.*)$", "^@patternfly/(.*)$", "^@bf2/(.*)$", "^@rhoas/(.*)$", "^[./]"] }.
[warn] Ignored unknown option { importOrderSeparation: true }.
```
> MGDOBR-600: Fix Prettier config

- package-lock.json
- package.json
- src/Keycloak.tsx
https://issues.redhat.com/browse/MGDOBR-466
The [integration with rh sso](https://issues.redhat.com/browse/MGDOBR-422) is completed. Updating keycloak config accordingly.
- `npm run start`
- rh login screen appears instead of our keycloak one
> MGDOBR-466: Update keycloak configuration to use rh sso

- .github/workflows/openapi-sdk-compatibility-check.yml
The created code should alert all engineers with new changes in sandbox/openapi/openapi.yaml, that were not downloaded/committed into sandbox-ui repository.
> [No Jira] Check the UI SDK is up to date with sandbox/openapi/openapi.yaml

- mocked-api/handlers.ts
- src/app/Instance/InstancesListPage/InstancesListPage.tsx
The current returned `size` param from API does not contain pagination size, but length of returned elements.
> [NO-JIRA]: Size issue on list of instances

- mocked-api/handlers.ts
JIRA: https://issues.redhat.com/browse/MGDOBR-730
Steps to test:
1. `npm run start:mocked`
2. when the application loads, open the browser developer tools
3. create a processor using the UI
4. go to the network panel of the browser developer tools and inspect the response of the creation request (POST /bridges/{bridgeId}/processors)
5. run the following fetch request from the browser developer tools console (replace `{bridgeId}` with the bridge used to create the processor) to get the list of processors including the one created at step 3:
```
fetch("https://event-bridge-event-bridge-prod.apps.openbridge-dev.fdvn.p1.openshiftapps.com/api/v1/bridges/{bridgeId/processors?page=0&size=10", {
"method": "GET"
});
```
> MGDOBR-730: [UI] Processors creation issues within mocked APIs

- src/app/Instance/InstancesListPage/InstancesListPage.tsx
JIRA: https://issues.redhat.com/browse/MGDOBR-752
- create a new SE instance
- wait for it to appear in the list
- there should be no link on its name until it reaches the `ready` status
> MGDOBR-752: Provide links to the SE Instance detail page only when the Instance is "ready"

- jest.config.ts
- src/App.tsx
- src/AppFederated.tsx
- src/AppMocked.tsx
- src/Keycloak.tsx
- src/contexts/SmartEventsContext.tsx
- src/hooks/useBridgesApi/useCreateBridgeApi.ts
- src/hooks/useBridgesApi/useDeleteBridgeApi.ts
- src/hooks/useBridgesApi/useGetBridgeApi.ts
- src/hooks/useBridgesApi/useGetBridgesApi.ts
- src/hooks/useProcessorsApi/useAddProcessorToBridgeApi.ts
- src/hooks/useProcessorsApi/useDeleteProcessorApi.ts
- src/hooks/useProcessorsApi/useGetProcessorApi.ts
- src/hooks/useProcessorsApi/useGetProcessorsApi.ts
- src/hooks/useProcessorsApi/useUpdateProcessorApi.ts
- tsconfig.json
JIRA: https://issues.redhat.com/browse/MGDOBR-782
Auth related functions, `apiBaseUrl` and `basename` are now passed as props to our application and shared internally through the new `SmartEventsContext`. 
`useAuth`, `useConfig` and `useBasename` are no longer used.
See jira link for further details.
> MGDOBR-782: Remove config, auth and basename contexts/hooks

- cypress/integration/ProcessorTest.ts
- package-lock.json
- package.json
- src/app/Processor/ProcessorEdit/ConfigurationForm/ConfigurationForm.tsx
https://issues.redhat.com/browse/MGDOBR-858
I have skipped several tests which start failing with MGDOBR-797 and cannot be fixed because the Processor part is under development. I expect other changes in UI. For example:
https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/79
I have introduced the `bugPresent` variable to be sure that we did not forget why such tests was skipped.
> MGDOBR-858: Fix ProcessorEdit test suite - MGDOBR-797 brings changes

- src/app/Processor/ProcessorEdit/ProcessorEdit.test.tsx
- src/app/Processor/ProcessorEdit/ProcessorEdit.tsx
- src/app/Processor/ProcessorEdit/useValidateProcessor.ts
- src/types/Processor.ts
JIRA: https://issues.redhat.com/browse/MGDOBR-732
Removing the ability to add a transformation template to source processors. It's not supported by APIs and it won't be for the foreseeable future.
To test it:
- Create a processor
- Select "source" type
- Transformation template field is not there anymore
- :champagne:
> MGDOBR-732: Remove transformation template section from source processors creation form

- src/app/Processor/ProcessorEdit/ConfigurationForm/CustomJsonSchemaBridge.tsx
- src/app/Processor/ProcessorEdit/ConfigurationForm/validator.ts
- src/app/Processor/ProcessorEdit/ProcessorEdit.test.tsx
JIRA: https://issues.redhat.com/browse/MGDOBR-904
Long story short: default values of optional fields inside action/source configuration forms were not included in the processor creation request. See jira link for more details.
- Create a new source processor
- Enter a processor name
- Select a source with fields that have default values (like `AWS S3 source`)
- Fill in required fields without touching optional fields with default values
- Submit the form
- Open the processor you just created
- Default values are there
- :champagne:
> MGDOBR-904: Default values handling within action/source configuration form of a processor

- mocked-api/schemasData.ts
JIRA: https://issues.redhat.com/browse/MGDOBR-906
Checking the new PubSub sink.
There's a potential issue with the `gcp_service_account_key` property. It seems to be a credential type of field but it doesn't have the `password` format. Logged the issue inside [MGDOBR-901
](https://issues.redhat.com/browse/MGDOBR-901)
Just updating the corresponding mock for now.
> MGDOBR-906: Verify new Google PubSub sink action

- mocked-api/handlers.ts
- openapi/generated/errorHelpers.ts
- openapi/generated/errors.ts
**Task**: https://issues.redhat.com/browse/MGDOBR-898
**Description**: Changing the function `getErrorCode` in `errorHelpers` to consider the first error returned by the APIs.
Consider that we could add new functions to the helper when we need to report multiple errors on the page or search for a particular error code among all returned error items.
> MGDOBR-898: Public API returns ErrorsResponse

- cypress/integration/ProcessorTest.ts
- mocked-api/schemasData.ts
JIRA: https://issues.redhat.com/browse/MGDOBR-907
Verifying recent changes on validations inside schemas and updating mocks.
The involved actions/sources seem to work as expected. 
There are many possible improvements, all of them already tracked inside [MGDOBR-901](https://issues.redhat.com/browse/MGDOBR-901) (password fields not properly declared, missing examples on some fields, tool-tips needing review, error messages etc,).
I've also noticed the introduction of the `$comment` property on some actions. Like all the properties of a field, it's forwarded down to the UI component responsible for rendering the input. This is causing another react warning inside the browser console. I've opened a new ticket ([MGDOBR-930](https://issues.redhat.com/browse/MGDOBR-930)) to find a solution to …
> MGDOBR-907: Verify updates on action/sources schema validation rules

- openapi/generated/errorHelpers.ts
- src/app/Instance/DeleteInstance/DeleteInstance.tsx
- src/app/Processor/DeleteProcessor/DeleteProcessor.tsx
As follow up of https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/pull/91 we are going to provide a utility function for retrieving the `reason` field from the first error item and using it in the delete modals.
> [NO-JIRA]: Retrieving the error cause from the first error item

- mocked-api/data.ts
Following PR #94, mocked processors needed a cleanup. 
They still had the data-shape properties that no longer exist in the Slack [action](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/blob/391cc7b0f2a4e4adca7691e6c874eeede137b367/mocked-api/schemasData.ts#L183)/[source](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/blob/391cc7b0f2a4e4adca7691e6c874eeede137b367/mocked-api/schemasData.ts#L688) schemas.
Thanks @vpellegrino for spotting this.
> NO-JIRA: Fix mocked processors following updates to schema catalog

- cypress/e2e/BasicTest.ts
The [PR](https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/899) changed a creation of a bridge via REST API.
E2E tests start failing. I have added new parameters into REST request.
> NO-JIRA: fix E2E test - REST was changed by MGDOBR-809

- src/app/Instance/InstanceDetails/InstanceDetails.tsx
When no endpoint URL is available (instance creation is still in progress) a skeleton will be shown:
In that image the missing endpoint has been forced programmatically, but you can simulate this situation with the real API.
> [NO-JIRA]: Skeleton when missing endpoint

- package-lock.json
- package.json
'npx depcheck' marked 'monaco-editor' as unused dependnecy
My guess we use 'monaco-editor' just for processor template? It seems still up and running.
> Remove 'monaco-editor' dependency

- cypress/integration/ActionTest.ts
- cypress/integration/SourceTest.ts
- locales/en/openbridge.json
- mocked-api/data.ts
- mocked-api/handlers.ts
- mocked-api/schemasData.ts
- src/app/Instance/CreateInstance/CreateInstance.test.tsx
- src/app/Instance/CreateInstance/CreateInstance.tsx
- src/app/Processor/CreateProcessorPage/CreateProcessorPage.tsx
- src/app/Processor/ProcessorDetail/ProcessorDetail.test.tsx
- src/app/Processor/ProcessorDetail/ProcessorDetailConfigParameters.tsx
- src/app/Processor/ProcessorEdit/ConfigurationEdit/ConfigurationEdit.tsx
- src/app/Processor/ProcessorEdit/ConfigurationForm/ConfigurationForm.tsx
- src/app/Processor/ProcessorEdit/ConfigurationForm/CustomJsonSchemaBridge.tsx
- src/app/Processor/ProcessorEdit/ProcessorEdit.test.tsx
- src/app/Processor/ProcessorEdit/ProcessorEdit.tsx
- src/utils/filterUtils.ts
- src/utils/processorUtils.test.ts
- src/utils/processorUtils.ts
JIRA: https://issues.redhat.com/browse/MGDOBR-872
This PR depends on:
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox/pull/863
I'm adding support for the new format of masked values (empty object, `{}`) inside processors.
To test this you will have to check your browser developer tools console and inspect network requests.
- `npm run start:mocked` (until the related PR is merged, you can only use the mocked APIs)
- open a bridge and click on create new processor
- select the sink type
- provide a processor name
- select an action with sensitive fields (like `AWS Lambda`)
- fill up the action configuration parameters
- click on the create processor button
- inspect the payload of the POST request that creates the processor. It will include the sensitive …
> MGDOBR-872: Manage masked values inside action/source configuration

- renovate.json
Updates to `react-monaco-editor` are causing issues because `@patternfly/react-code-editor` requires a specific version of it (`^0.41.2`) as peer dependecy.
```
Found file in cache: /tmp/containerbase/7576b42decc67f70b61585f41c5074bea75c260886346e567578ea0e0dc2d571/node-v16.17.0-linux-x64.tar.xz
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: smartevents-ui@0.0.1
npm ERR! Found: react-monaco-editor@0.50.1
npm ERR! node_modules/react-monaco-editor
npm ERR!   react-monaco-editor@"0.50.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-monaco-editor@"^0.41.2" from @patternfly/react-code-editor@4.72.8
npm ERR! node_modules/@patternfly/react-code-editor
npm ERR! …
```
> NO-JIRA: Prevent updates on react-monaco-editor

- src/app/components/Table/Table.tsx
Removing ts generics usage within `RenderActions` because it's not really necessary and it's causing issues with renovate while updating typescript.
> [NO-JIRA] Fix TableRow type inside RenderActions

- src/app/Instance/InstancePage/ErrorHandlingTabContent.tsx
- src/app/Processor/ProcessorConfigParameters/ProcessorConfigParameters.test.tsx
- src/app/Processor/ProcessorConfigParameters/ProcessorConfigParameters.tsx
- src/app/Processor/ProcessorDetail/ProcessorDetail.test.tsx
- src/app/Processor/ProcessorDetail/ProcessorDetail.tsx
JIRA: https://issues.redhat.com/browse/MGDOBR-1059
Steps to test:
- Create a bridge with webhook error handler **without** providing a user/password combination
- Wait for the bridge to get ready
- Open the bridge, click on the `Error handling` link
- The password field value is displayed as `Property not configured` (it was a masked value before)
Same thing can be tested on a sink processor with webhook action. It's the same component used there too.
> MGDOBR-1059: Optional secrets value displayed as masked value even when the value was not set

- src/app/Instance/CreateInstance/CreateInstance.tsx
- src/app/Processor/ProcessorEdit/ConfigurationForm/CustomJsonSchemaBridge.tsx
- src/app/Processor/ProcessorEdit/ProcessorEdit.tsx
JIRA: https://issues.redhat.com/browse/MGDOBR-981
Unfortunately there's no standard way to prevent browsers from asking to store credentials. 
This PR is focusing only on the `autocomplete` feature, to at least prevent form values from being auto-filled.
Steps to test it (on Chrome):
- Create a processor with an action/source with a password field
- Store the credentials
- Create another processor and check that the saved credentials are not auto-filled.
> MGDOBR-981: Action/Source configuration - browser saving/restoring form data

- .github/workflows/quality-checks-e2e.yml
Due to recently introduced conditional checkout
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/commit/3f6aa6e825946f8da43177616113b577f9108690
The repository is not cloned and this GHA fails:
- https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/runs/8249926875?check_suite_focus=true
> [No Jira] Remove conditional checkout

- .github/workflows/quality-checks-e2e.yml
Due to recently introduced conditional checkout
https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/commit/3f6aa6e825946f8da43177616113b577f9108690
The repository is not executed as expected.
> no-jira: revert changes which was presented by PR #172

- package-lock.json
- package.json
The package was indicated as unused by 'npx depcheck'. Attaching output of the command below:
```
Unused dependencies
* monaco-editor-webpack-plugin
Unused devDependencies
* @pmmmwh/react-refresh-webpack-plugin
* @types/jest
* babel-jest
* babel-loader
* bundle-loader
* css-loader
* cssnano
* eslint-plugin-import
* eslint-plugin-jsx-a11y
* eslint-plugin-prettier
* file-loader
* null-loader
* react-refresh
* react-refresh-typescript
* source-map-loader
* style-loader
* ts-jest
* ts-loader
* ts-node
* typescript
* url-loader
* webpack-cli
* webpack-dev-server
Missing dependencies
* regenerator-runtime: ./setupJest.ts
* @app/components: ./src/App.tsx
* @app/Routes: ./src/App.tsx
* @contexts/SmartEventsContext: ./src/App.tsx
* @utils/processorUtils: ./src/utils/processorUtils.test.ts
* …
```
> [no-jira] Remove unused 'monaco-editor-webpack-plugin'

- webpack.common.js
JIRA: https://issues.redhat.com/browse/MGDOBR-1108
Issue was caused by the update to `css-loader@6.7.1` introduced with #164.
As reported by `css-loader` [release notes](https://github.com/webpack-contrib/css-loader/releases/tag/v6.0.0), some changes to the webpack configuration for assets fix the problem.
To test that the Red Hat font is properly used, inspect a text node with chrome developer tools and look for the computed tab.
___
Before
After
> MGDOBR-1108: Red Hat font not loading properly

- src/app/Processor/ProcessorEdit/ConfigurationForm/CustomJsonSchemaBridge.tsx
JIRA: https://issues.redhat.com/browse/MGDOBR-930
Filtering `$comment` and `isSecret` props causing react console warnings. They should not be forwarded down to uniforms fields.
> MGDOBR-930: Warnings about invalid props inside forms generated with json schema

- cypress/integration/instance/InstanceEdit.ts
- src/app/Instance/InstancesListPage/InstancesListPage.tsx
JIRA: https://issues.redhat.com/browse/MGDOBR-1117
1. `npm run start:mocked`
2. click on the bridge `Instance one` and edit its error handling configuration
3. save the change
4. after being redirected to the bridge list, `Instance one` status is `Creating` and the message `This is taking longer than expected.` is not shown anymore
> MGDOBR-1117: Status label of bridges and modified_at support

- cypress/integration/ActionTest.ts
- src/app/Instance/ErrorHandling/ErrorHandlingDetail.test.tsx
- src/app/Instance/ErrorHandling/ErrorHandlingDetail.tsx
- src/app/Instance/ErrorHandling/ErrorHandlingEdit.css
- src/app/Instance/ErrorHandling/ErrorHandlingEdit.tsx
- src/app/Instance/ErrorHandling/ErrorHandlingPageSection.tsx
- src/app/Instance/InstancePage/ErrorHandlingTabContent.css
- src/app/Instance/InstancePage/ErrorHandlingTabContent.tsx
- src/app/Instance/InstancePage/InstancePage.css
- src/app/Instance/InstancePage/InstancePage.tsx
- src/app/Instance/InstancePage/ProcessorsTabContent.tsx
- src/app/Processor/ProcessorEdit/ProcessorEdit.css
- src/app/Processor/ProcessorEdit/ProcessorEdit.tsx
- src/app/Processor/ProcessorEdit/ProcessorEditSkeleton.tsx
- src/app/components/StickyActionsLayout/StickyActionsLayout.css
- src/app/components/StickyActionsLayout/StickyActionsLayout.tsx
JIRA: https://issues.redhat.com/browse/MGDOBR-1129
This PR implements the "full height layout with fixed actions" for the error handling tab of bridges.
I did some investigation before starting working on it. 
PF offers a "sticky actions" solution with the `PageSection` component ([example](https://www.patternfly.org/v4/components/page/html-demos/#sticky-section-bottom)). In order to use it though, the involved `PageSection`'s need to be all at the same _root_ level. In our case, the EH actions are deep down in the tree from where the page layout resides (`InstancePage` :arrow_right: `ErrorHandlingTabContent` :arrow_right: `ErrorHandlingEdit`). Another hurdle comes with the presence of PF `Tabs` within `InstancePage`, because each `Tab` interfere with …
> MGDOBR-1129: Refactor the Instance Page layout for adherence with UX prototype

- package-lock.json
- package.json
It was introduced (by me actually) with #24 but it's not required for msw.
> NO-JIRA: remove unused @types/node dependency

- cypress/integration/instance/InstanceCreation.ts
The `Smart Events UI :: Dev :: Quality Checks` mostly ends with this error:
```
<![CDATA[ CypressError: Timed out retrying after 120000ms: `cy.should()` failed because this element is detached from the DOM. `<div data-ouia-component-id="steps-count" data-ouia-component-type="QE/StackItem" class="pf-l-stack__item">1 of 3 ...</div>` Cypress requires elements be attached in the DOM to interact with them. The previous command that ran was: > `cy.ouiaId()` This DOM element likely became detached somewhere between the previous and current command. Common situations why this happens: - Your JS framework re-rendered asynchronously - Your app code reacted to an event firing and removed the element You typically need to re-query for the element or add 'guards' which delay Cypress from running new …
```
> [no-jira] fix status popover test DOM instability

- package-lock.json
- public/mockServiceWorker.js
See security alert: https://github.com/5733d9e2be6485d52ffa08870cabdee0/sandbox-ui/security/dependabot/6
`@xmldom/xmldom` versions `< 0.7.7` have vulnerability issues. We already fixed this dep issues in the past with `npm audit fix`, moving from `0.7.5` to `0.7.6` (#238).
We would like to avoid doing this for each minor/patch release until we get a good one.
This is the xmldom dependency tree:
```
smartevents-ui@0.0.1 /home/remanuel/workspace/sandbox-ui
└─┬ msw@0.47.4
└─┬ @mswjs/interceptors@0.17.5
└── @xmldom/xmldom@0.7.6
```
Unfortunately there's no straightforward way to update xmldom by updating its parent deps. [`@mswjs/interceptors`](https://github.com/mswjs/interceptors/blob/aff787ee28e58737662b31b93e2b7f24faad7beb/package.json#L71) is listing it with `"@xmldom/xmldom": "^0.8.3"`, …
> NO-JIRA: Fix @xmldom/xmldom security issues

- cypress/integration/instance/InstanceCreation.ts
- mocked-api/handlers.ts
- src/hooks/useBridgesApi/useCreateBridgeApi.ts
JIRA: https://issues.redhat.com/browse/MGDOBR-1196
Steps to test:
- run the app against mocked APIs with `npm run start:mocked`
- click on `Create Smart Events Instance`
- enter a name containing `error-test`, like `bridge error-test`
- submit the form by clicking on `Create Smart Events Instance`
- after the API request is done, the dialog exits its loading status and the generic error alert appears on top
> MGDOBR-1196: "Create bridge" dialog hangs after API unexpected managed errors

- src/app/Instance/InstancePage/InstancePage.tsx
- src/app/Instance/InstancePage/ProcessorsTabContent.tsx
JIRA: https://issues.redhat.com/browse/MGDOBR-1203
- Create a bridge instance with Incorrect parameters to enter into Failed state.
- Open the failed bridge instance detail page.
- Create processor button will be disabled for the failed bridge instance.
> MGDOBR-1203:Disable processor creation for FAILED SE instances

- cypress/integration/instance/InstanceCreation.ts
- cypress/integration/instance/InstanceStatuses.ts
- cypress/integration/instance/Pagination.ts
This PR should fix several instabilities in the `Smart Events UI :: Mocked :: Quality Checks`.
- **when a bridge instance is created I have remove the dynamic assertion of the SE Status Popover dialog** (accepted -> preparing -> provisioning -> ready). The main problem is that update frequency of UI might hide some statuses like accepted -> provisioning -> ready or accepted -> preparing -> ready.
- **the InstanceStatuses test requires scrolling** to the desired bridge instance.
- **the Pagination test needs the waiting rutine** because the deletion of the bridge instance updates the Instances Page and shows skeletons. Previously the test was waiting on `instance ten` which was in state deleting (not ready). I have changed it to `instance one` because it is not affected by this test.
> NO JIRA: fix instabilities

- locales/en/smart-events.json
- mocked-api/handlers.ts
- src/app/Instance/InstancePage/ProcessorsTabContent.tsx
- src/app/Instance/InstancesListPage/InstancesListPage.tsx
- src/app/components/EmptyState/EmptyStateNoData.tsx
- src/app/components/EmptyState/EmptyStateNoResults.tsx
- src/hooks/useBridgesApi/useGetBridgesApi.ts
- src/hooks/useProcessorsApi/useGetProcessorsApi.ts
- src/hooks/useTablePageParams/useTablePageParams.ts
- src/utils/statusUtils.ts
**Jira:** https://issues.redhat.com/browse/MGDOBR-1229
A few points:
1. Query params are preserved when going back with the browser's button but not when clicking on a link in the application. What should we do about it? What is the expected user experience?
2. I created a hook for managing page parameters for pages using table overviews to favor reusability. We can make this hook configurable (for instance, I may want to add the `name` filter and not `status`). Just let me know.
3. I just added a few statuses supported by the API. Should we add all of them? Support any other not in the current list?
4. It seems we have a defect (in `app-services-ui-component`) related to multiple chips when removing one of them:
> MGDOBR-1229: Add support for filter in our overview pages

- src/app/components/EmptyState/EmptyStateNoData.tsx
- src/app/components/EmptyState/EmptyStateNoResults.tsx
`EmptyState` stories inside storybook have some missing translations.
According to `react-i18next` [docs](https://react.i18next.com/latest/trans-component), the `Trans` component does not re-render when the dictionary is loaded/changed. This is an issue when running components in isolation without any `useTranslation` usage triggering re-renders.
It should be fixed now.
> NO-JIRA: Fix Trans component usage 

- locales/en/smart-events.json
- src/app/components/POCs/ProcessorEditHeader/ProcessorEditHeader.css
- src/app/components/POCs/ProcessorEditHeader/ProcessorEditHeader.stories.tsx
- src/app/components/POCs/ProcessorEditHeader/ProcessorEditHeader.tsx
JIRA: https://issues.redhat.com/browse/MGDOBR-1339
Initial implementation of the processor editing header.
PF doesn't provide a react component for inline editing, so I've used [their html code only](https://www.patternfly.org/v4/components/inline-edit).
I didn't add the actions dropdown because it's likely actions will not be available while creating/editing a processor. We can come back to this later if necessary.
> MGDOBR-1339: "Create processor" header component poc

- cypress/integration/instance/InstanceStatuses.ts
- cypress/integration/instance/Pagination.ts
- cypress/utils/Util.ts
During the last month the execution of:
- [InstanceStatuses.ts](https://github.com/sjamboro/sandbox-ui/blob/nojira-fixinstability230124/cypress/integration/instance/InstanceStatuses.ts)
- [Pagination](https://github.com/sjamboro/sandbox-ui/blob/nojira-fixinstability230124/cypress/integration/instance/Pagination.ts)
started failing (randomly).
InstanceStatuses failure might be connected with this state:
I have added a wait rutine to the next update of the table.
> NO JIRA: Fix instability of Pagination and InstanceStatus Test
